### ISSUE TITLE
Compatible with ELM327 II Bluetooth Can-Bus dongle

### ISSUE THREAD

**Issue by bassmaster187** [JonnoFTW/rpi-can-logger#1]
Hi,

I'm using scanmytesla app with ELM327 II Bluetooth dongle to monitor battery temperature. 
Is your project compatible with this bluetooth donge, so I can log can-messages to the sd-card?

**Comment by JonnoFTW** [comment]
No, this does not support input via Bluetooth from an elm327 device. This software is not designed to implement the elm327 protocol.


It would be easier to write another program that reads the Bluetooth output from your device and log that, there should already exist stuff to do this.
