### ISSUE TITLE
Clarification of README comment about WiFi performance issues with mounted PiCAN

### ISSUE THREAD

**Issue by willik** [JonnoFTW/rpi-can-logger#5]
Hello! This question is about some information in the README, and isn't really about any issue with the code :). Anyway, concerning this quote from the README..

> If you want WiFi to work with the PiCAN2 shield attached, you'll need to unsolder the GPIO pins and drop them to the bottom and reattach the shield

Could you elaborate a bit on the WiFi performance issues with PiCAN2? I take it the PiCAN2 blocked the WiFi antenna such that WiFi was unusable. And it sounds like your solution was to move the GPIO pins to the other side of the Pi, effectively mounting PiCAN2 on the opposite side of the Pi, leaving the WiFi antenna more exposed.

Please confirm if my interpretation of the quote is correct, cheers!

**Comment by JonnoFTW** [comment]
Your interpretation is correct. The wifi board component on the rpi3 was very close to a large metal block on the pican2 which prevented wifi from working well ( I think it basically blocked all signals, but this was a few years ago). 

In our production environment, we eventually moved to a pi0 which a custom CAN shield for which wifi was not blocked at all.
