### ISSUE TITLE
Problem during logging

### ISSUE THREAD

**Issue by nagyapi** [JonnoFTW/rpi-can-logger#6]
Hi,

First of all, thank you for your work. 
I would like to ask for a little help. I've installed the repository on a Raspberry Pi Zero 2 W, but I'm stuck. I tried testing the logging feature, but it was unsuccessful, or I may have missed something. I sent messages via a PCAN USB adapter from PCAN-View to an MCP2515 CAN bus adapter (
![mcp2515](https://github.com/JonnoFTW/rpi-can-logger/assets/152105546/2686b3ac-a6f5-46b6-8663-e627649b9c70)
which I modified for 3.3V supply and 16 MHz)

Here is the insalled .yaml configuration file:
```
channel: can0
disable-gps: true
fms: true
interface: socketcan
log-bluetooth: false
log-folder: ~/log/can-log/
log-level: warning
log-messages: ~/log/can-log/messages/
log-pids: [FMS_ENGINE_HOURS, FMS_FUEL_CONSUMPTION, FMS_ENGINE_TEMP, FMS_FUEL_ECONOMY]
log-size: 32
log-trigger: FMS_ENGINE_HOURS
pid-file: ~/log/can-log.pid
sniffing: false
tesla: false
vehicle-id: scania
verbose: true
``` 
Changing "sniffing: false" to "true" did not solve the problem.

I checked the status of the rpi-logger.service:

- Loaded: loaded (/lib/systemd/system/rpi-logger.service; enabled; vendor present: enabled)

- Active: active (running)

After checking the .json file I see this:
{"vid": "scania", "trip_id": "20240630_150437_P1aGqk_scania", "trip-sequence": 83}

If I run the [can_sniff_test.py](https://github.com/JonnoFTW/rpi-can-logger/blob/master/tests/can_sniff_test.py) I see the messages.

What could be wrong?
Thanks!

**Comment by JonnoFTW** [comment]
What kind of vehicle are you running on? You need to ensure that whatever is sending the CAN data is sending on the same PIDs as specified in the config.

The PID code to log-pids mapping is here: https://github.com/JonnoFTW/rpi-can-logger/blob/master/rpi_can_logger/logger/fms_pids.py#L247-L286

**Comment by nagyapi** [comment]
Sorry, the sample message was wrong.  Now it works. 
Thank you!
